<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160307185458 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE cron_formbuilder_backendmodule_domain_model_formsubmission (persistence_object_identifier VARCHAR(40) NOT NULL, nodeidentifier VARCHAR(255) NOT NULL, createdat DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE cron_formbuilder_backendmodule_domain_model_formelementvalue (persistence_object_identifier VARCHAR(40) NOT NULL, formsubmission VARCHAR(40) DEFAULT NULL, nodeidentifier VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, INDEX IDX_289263D3E79944E2 (formsubmission), INDEX IDX_289263D31D775834 (value), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE cron_formbuilder_backendmodule_domain_model_formelementvalue ADD CONSTRAINT FK_289263D3E79944E2 FOREIGN KEY (formsubmission) REFERENCES cron_formbuilder_backendmodule_domain_model_formsubmission (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE cron_formbuilder_backendmodule_domain_model_formelementvalue DROP FOREIGN KEY FK_289263D3E79944E2");
		$this->addSql("DROP TABLE cron_formbuilder_backendmodule_domain_model_formelementvalue");
		$this->addSql("DROP TABLE cron_formbuilder_backendmodule_domain_model_formsubmission");
	}
}
